# 2 Linear Algebra

## The Trace Operator

In [1]:
import torch

In [2]:
A = torch.FloatTensor([[3,7,4],[5,9,1],[2,2,8]])
print("A: \n", A)
print("Trace of A: \n", A.diag().sum())
print("Trace of A (using the function in PyTorch): \n", A.trace())

A: 
 tensor([[3., 7., 4.],
        [5., 9., 1.],
        [2., 2., 8.]])
Trace of A: 
 tensor(20.)
Trace of A (using the function in PyTorch): 
 tensor(20.)


In [3]:
print("Frobenius norm of A: \n", (A ** 2).sum() ** 1/2 )
print("Frobenius norm of A (using trace): \n", A.matmul(A.t()).trace() ** 1/2)

Frobenius norm of A: 
 tensor(126.5000)
Frobenius norm of A (using trace): 
 tensor(126.5000)


In [4]:
A = torch.randint(1, 10, [3, 3])
B = torch.randint(1, 10, [3, 3])
C = torch.randint(1, 10, [3, 3])

print("A: \n", A)
print("B: \n", B)
print("C: \n", C)
print("Tr(ABC)", A.matmul(B.matmul(C)).trace())
print("Tr(BCA)", B.matmul(C.matmul(A)).trace())
print("Tr(CAB)", C.matmul(A.matmul(B)).trace())

A: 
 tensor([[7, 5, 3],
        [3, 2, 4],
        [3, 6, 1]])
B: 
 tensor([[1, 2, 2],
        [1, 3, 8],
        [4, 8, 6]])
C: 
 tensor([[3, 1, 3],
        [4, 6, 4],
        [4, 5, 4]])
Tr(ABC) tensor(1494)
Tr(BCA) tensor(1494)
Tr(CAB) tensor(1494)


In [5]:
A = torch.randint(1, 10, [3, 5])
B = torch.randint(1, 10, [5, 3])
AB = A.matmul(B)
BA = B.matmul(A)
print("A: \n", A)
print("B: \n", B)
print("AB: \n", AB)
print("BA: \n", BA)
print("Tr(AB): \n", AB.trace())
print("Tr(BA): \n", BA.trace())

A: 
 tensor([[1, 8, 5, 1, 3],
        [7, 2, 4, 5, 3],
        [9, 2, 1, 9, 4]])
B: 
 tensor([[9, 6, 7],
        [2, 5, 4],
        [9, 8, 2],
        [8, 1, 2],
        [6, 8, 5]])
AB: 
 tensor([[ 96, 111,  66],
        [161, 113,  90],
        [190, 113, 111]])
BA: 
 tensor([[114,  98,  76, 102,  73],
        [ 73,  34,  34,  63,  37],
        [ 83,  92,  79,  67,  59],
        [ 33,  70,  46,  31,  35],
        [107,  74,  67,  91,  62]])
Tr(AB): 
 tensor(320)
Tr(BA): 
 tensor(320)
