# 2 Linear Algebra

## 2.1 Scalars, Vectors, Matrices and Tensors

In [1]:
import torch

In [2]:
print("Scalar: \n", torch.tensor([1]))
print("Horizontal Vector: \n", torch.ones(4))
print("Vertical Vector: \n", torch.ones(4).reshape(-1, 1))
print("Matrix: \n", torch.ones([4, 3]))
print("Tensor: \n", torch.ones([4, 3, 2]))

Scalar: 
 tensor([1])
Horizontal Vector: 
 tensor([1., 1., 1., 1.])
Vertical Vector: 
 tensor([[1.],
        [1.],
        [1.],
        [1.]])
Matrix: 
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
Tensor: 
 tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])


Note that in  Pytorch, scalar, vector, matrix, tensor are all dealt as Tensor objects as tensor is generalization of them.

In [3]:
# Transpose
A = torch.randint(1, 100, [4, 3])
print("A: \n", A)
print("Transpose of A: \n", A.t())

A: 
 tensor([[47,  1, 56],
        [40,  9, 50],
        [ 5, 39, 11],
        [32, 63, 59]])
Transpose of A: 
 tensor([[47, 40,  5, 32],
        [ 1,  9, 39, 63],
        [56, 50, 11, 59]])


In [4]:
# Adding a scalar, vector or matrix to another matrix
A = torch.randint(1, 10, [3, 2], dtype=torch.int32)
B = torch.randint(1, 10, [3, 2], dtype=torch.int32)
v = torch.randint(1, 10, [3], dtype=torch.int32)
c = torch.IntTensor([10])

print("A: \n", A)
print("B: \n", B)
print("v: \n", v.reshape(-1, 1))
print("c: \n", c)
print("A + c: \n", A + c)
print("A + B: \n", A + B)
print("A + v: \n", A + v.reshape(-1, 1))

A: 
 tensor([[5, 2],
        [5, 6],
        [1, 7]], dtype=torch.int32)
B: 
 tensor([[1, 5],
        [1, 5],
        [9, 2]], dtype=torch.int32)
v: 
 tensor([[2],
        [3],
        [2]], dtype=torch.int32)
c: 
 tensor([10], dtype=torch.int32)
A + c: 
 tensor([[15, 12],
        [15, 16],
        [11, 17]], dtype=torch.int32)
A + B: 
 tensor([[ 6,  7],
        [ 6, 11],
        [10,  9]], dtype=torch.int32)
A + v: 
 tensor([[7, 4],
        [8, 9],
        [3, 9]], dtype=torch.int32)


Here we converted the horizontal vector to vertical as the size of the row should be the same between each other.