# 2 Linear Algebra

## 2.2 Multiplying Matrices and Vectors

In [1]:
import torch

In [2]:
A = torch.IntTensor([[9, 9], [2, 2], [4, 6]])
B = torch.IntTensor([[4, 5, 4, 3], [2, 5, 1, 9]])
C = A.matmul(B)

print("A: \n", A)
print("B: \n", B)
print("C: \n", C)

A: 
 tensor([[9, 9],
        [2, 2],
        [4, 6]], dtype=torch.int32)
B: 
 tensor([[4, 5, 4, 3],
        [2, 5, 1, 9]], dtype=torch.int32)
C: 
 tensor([[ 54,  90,  45, 108],
        [ 12,  20,  10,  24],
        [ 28,  50,  22,  66]], dtype=torch.int32)


If you don't understand what's going on here, you can refer to the following resource:
[Mechanics of Matrix Multiplication (wikibooks.org)](https://en.wikibooks.org/wiki/Linear_Algebra/Mechanics_of_Matrix_Multiplication).

In [3]:
A = torch.randint(1, 10, [4, 3], dtype=torch.int32)
B = torch.randint(1, 10, [3, 3], dtype=torch.int32)
C = torch.randint(1, 10, [3, 3], dtype=torch.int32)

print("A: \n", A)
print("B: \n", B)
print("C: \n", C)
print("A(B+C): \n", A.matmul(B + C))
print("AB + AC: \n", A.matmul(B) + A.matmul(C))
print("A(BC): \n", A.matmul(B.matmul(C)))
print("(AB)C: \n", A.matmul(B).matmul(C))

A: 
 tensor([[9, 8, 7],
        [5, 4, 3],
        [3, 3, 9],
        [6, 5, 3]], dtype=torch.int32)
B: 
 tensor([[1, 5, 4],
        [8, 4, 3],
        [9, 8, 6]], dtype=torch.int32)
C: 
 tensor([[9, 1, 2],
        [1, 8, 9],
        [5, 9, 8]], dtype=torch.int32)
A(B+C): 
 tensor([[260, 269, 248],
        [128, 129, 120],
        [183, 207, 180],
        [147, 147, 138]], dtype=torch.int32)
AB + AC: 
 tensor([[260, 269, 248],
        [128, 129, 120],
        [183, 207, 180],
        [147, 147, 138]], dtype=torch.int32)
A(BC): 
 tensor([[1867, 2118, 2285],
        [ 891, 1034, 1113],
        [1446, 1575, 1707],
        [1016, 1178, 1268]], dtype=torch.int32)
(AB)C: 
 tensor([[1867, 2118, 2285],
        [ 891, 1034, 1113],
        [1446, 1575, 1707],
        [1016, 1178, 1268]], dtype=torch.int32)


Oh by the way, note that torch.randint returns torch.LongTensor instead of torch.IntTensor unless we specify dtype as torch.int32 explicitly.

In [4]:
A = torch.IntTensor([[1,2,3],[4,5,6],[7,8,9]])
B = torch.IntTensor([[1,4,7],[2,5,8],[3,5,9]])
x = torch.randint(1, 10, [5])
y = torch.randint(1, 10, [5])

print("A: \n", A)
print("B: \n", B)
print("AB: \n", A.matmul(B))
print("BA: \n", B.matmul(A))
print("x: \n", x)
print("y: \n", y)
print("x^Ty: \n", x.dot(y))
print("y^Tx: \n", y.dot(x))
print("(AB)^T: \n", A.matmul(B).t())
print("B^TA^T: \n", B.t().matmul(A.t()))

A: 
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=torch.int32)
B: 
 tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 5, 9]], dtype=torch.int32)
AB: 
 tensor([[ 14,  29,  50],
        [ 32,  71, 122],
        [ 50, 113, 194]], dtype=torch.int32)
BA: 
 tensor([[ 66,  78,  90],
        [ 78,  93, 108],
        [ 86, 103, 120]], dtype=torch.int32)
x: 
 tensor([4, 3, 5, 6, 5])
y: 
 tensor([3, 6, 6, 2, 2])
x^Ty: 
 tensor(82)
y^Tx: 
 tensor(82)
(AB)^T: 
 tensor([[ 14,  32,  50],
        [ 29,  71, 113],
        [ 50, 122, 194]], dtype=torch.int32)
B^TA^T: 
 tensor([[ 14,  32,  50],
        [ 29,  71, 113],
        [ 50, 122, 194]], dtype=torch.int32)


In [5]:
A = torch.Tensor([[1, -2, 3], [3, 1, -5], [-2, 6, -9]])
b = torch.Tensor([1, -4, -2])

print("A: \n", A)
print("b: \n", b)
print("Ax = b; x = ?: \n", torch.gesv(b, A)[0])

A: 
 tensor([[ 1., -2.,  3.],
        [ 3.,  1., -5.],
        [-2.,  6., -9.]])
b: 
 tensor([ 1., -4., -2.])
Ax = b; x = ?: 
 tensor([[1.],
        [3.],
        [2.]])
