# 2 Linear Algebra

## 2.3 Identity and Inverse Matrices

In [1]:
import torch

In [2]:
A = torch.Tensor([[1, -2, 3], [3, 1, -5], [-2, 6, -9]])
A_inv = A.inverse()
b = torch.Tensor([1, -4, -2])

print("A: \n", A)
print("A^-1: \n", A_inv)
print("b: \n", b)

A: 
 tensor([[ 1., -2.,  3.],
        [ 3.,  1., -5.],
        [-2.,  6., -9.]])
A^-1: 
 tensor([[ 3.0000e+00, -2.9802e-08,  1.0000e+00],
        [ 5.2857e+00, -4.2857e-01,  2.0000e+00],
        [ 2.8571e+00, -2.8571e-01,  1.0000e+00]])
b: 
 tensor([ 1., -4., -2.])


In [3]:
print("A^-1A: \n", A.inverse().matmul(A).round().int())

A^-1A: 
 tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]], dtype=torch.int32)


Here I'm doing very sloppy rounding just for showing the identity matrix by a very simple way. So please don't do this on your production code.

In [4]:
print("Ax = b; x = ?: \n", A_inv.mv(b))

Ax = b; x = ?: 
 tensor([1.0000, 3.0000, 2.0000])
