# 2 Linear Algebra

## 2.6 Special Kinds of Matrices and Vectors

In [1]:
import torch

### Diagonal matrix

In [2]:
v = torch.randint(1, 10, [5]).float()
D = torch.diag(v)
print("v: \n", v)
print("Diagonal matrix D: \n", D)

v: 
 tensor([1., 6., 5., 1., 9.])
Diagonal matrix D: 
 tensor([[1., 0., 0., 0., 0.],
        [0., 6., 0., 0., 0.],
        [0., 0., 5., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 9.]])


In [3]:
print("Inverse of D: \n", D.inverse())

Inverse of D: 
 tensor([[1.0000, 0.0000, 0.0000, 0.0000, -0.0000],
        [0.0000, 0.1667, 0.0000, 0.0000, -0.0000],
        [0.0000, 0.0000, 0.2000, 0.0000, -0.0000],
        [0.0000, 0.0000, 0.0000, 1.0000, -0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.1111]])


In [4]:
x = torch.randint(1, 10, [5]).float()
print("diag(v)x: \n", D.mv(x))
print("Hadamard product: \n", v * x)

diag(v)x: 
 tensor([ 3., 48., 40.,  2., 45.])
Hadamard product: 
 tensor([ 3., 48., 40.,  2., 45.])


### Symmetric matrix

In [5]:
A = torch.IntTensor([[1, 3, 5], [3, 4, 2], [5, 2, 1]])
print("A: \n", A)
print("Transpose of A: \n", A.t())
print("A equals to the transpose of A?:", torch.all(A.eq(A.t())).item() == 1)

A: 
 tensor([[1, 3, 5],
        [3, 4, 2],
        [5, 2, 1]], dtype=torch.int32)
Transpose of A: 
 tensor([[1, 3, 5],
        [3, 4, 2],
        [5, 2, 1]], dtype=torch.int32)
A equals to the transpose of A?: True


### Unit vector

In [6]:
v = torch.Tensor([0.6, 0.8])
print("The L2 norm of v:", v.norm(2).item())

The L2 norm of v: 1.0


### Orthogonal vector and matrix

In [7]:
import math

# orthogoal vector
x = torch.Tensor([0, 5])
y = torch.Tensor([4, 0])
print("xTy: \n", x.dot(y))

# orthonormal vector
x = torch.Tensor([0.6, 0, 0.8, 0])
y = torch.Tensor([0, 0.6, 0, 0.8])
print("xTy (orthonormal): \n", x.dot(y))
print("L2 norm of x and y(orthonormal): \n", x.norm(2), y.norm(2))

# orthogonal matrix
sqrt_2 = math.sqrt(2)
A = torch.Tensor([[1/sqrt_2, 0, -1/sqrt_2], [1/2, sqrt_2/2, 1/2], [1/2, -sqrt_2/2, 1/2]])
print("Orthogonal matrix A: \n", A)
print("A^TA: \n", A.t().matmul(A).round()) # sloppy rounding again
print("AA^T: \n", A.matmul(A.t()).round())
print("A^-1: \n", A.inverse())
print("A^T: \n", A.t())

xTy: 
 tensor(0.)
xTy (orthonormal): 
 tensor(0.)
L2 norm of x and y(orthonormal): 
 tensor(1.) tensor(1.)
Orthogonal matrix A: 
 tensor([[ 0.7071,  0.0000, -0.7071],
        [ 0.5000,  0.7071,  0.5000],
        [ 0.5000, -0.7071,  0.5000]])
A^TA: 
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
AA^T: 
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
A^-1: 
 tensor([[ 7.0711e-01,  5.0000e-01,  5.0000e-01],
        [ 1.2688e-08,  7.0711e-01, -7.0711e-01],
        [-7.0711e-01,  5.0000e-01,  5.0000e-01]])
A^T: 
 tensor([[ 0.7071,  0.5000,  0.5000],
        [ 0.0000,  0.7071, -0.7071],
        [-0.7071,  0.5000,  0.5000]])
