# 2 Linear Algebra

## The Moore-Penrose Pseudoinverse

In [1]:
import torch

In [2]:
A = torch.FloatTensor([[5,8],[2,9],[3,3]])
print("A: \n", A)

A: 
 tensor([[5., 8.],
        [2., 9.],
        [3., 3.]])


In [3]:
U, D_tmp, V = A.svd(some=False)

D = torch.zeros([U.size()[0], V.size()[0]])
D[:-1,:] = D_tmp.diag()

print("U: \n", U)
print("D: \n", D)
print("V: \n", V)
print("Singular decomposition of A: \n", U.matmul(D).matmul(V.t()))

U: 
 tensor([[-0.6885,  0.4500, -0.5688],
        [-0.6636, -0.7072,  0.2438],
        [-0.2926,  0.5453,  0.7855]])
D: 
 tensor([[13.5874,  0.0000],
        [ 0.0000,  2.7171],
        [ 0.0000,  0.0000]])
V: 
 tensor([[-0.4156,  0.9095],
        [-0.9095, -0.4156]])
Singular decomposition of A: 
 tensor([[5.0000, 8.0000],
        [2.0000, 9.0000],
        [3.0000, 3.0000]])


In [4]:
D_pseudoinverse = torch.where(D > 0, D ** -1, torch.Tensor([0]))
A_pseudoinverse = U.matmul(D_pseudoinverse).matmul(V.t())
print("D: \n", D)
print("D+ (Pseudoinverse of D): \n", D_pseudoinverse)
print("A+ (Pseudoinverse of A): \n", A_pseudoinverse)
print("A+^-1A: \n", A_pseudoinverse.t().matmul(A).int())

D: 
 tensor([[13.5874,  0.0000],
        [ 0.0000,  2.7171],
        [ 0.0000,  0.0000]])
D+ (Pseudoinverse of D): 
 tensor([[0.0736, 0.0000],
        [0.0000, 0.3680],
        [0.0000, 0.0000]])
A+ (Pseudoinverse of A): 
 tensor([[ 0.1717, -0.0227],
        [-0.2164,  0.1526],
        [ 0.1915, -0.0638]])
A+^-1A: 
 tensor([[1, 0],
        [0, 1]], dtype=torch.int32)
