# 2 Linear Algebla

## 2.4 Linear Dependence and Span

In [1]:
import torch

### Linearly dependent matrix example
We'll get an error when we try to calculate the inverse of the following matrix because [1, 2, 3] and [2, 4, 6] is linearly dependent, which means the matrix has redundant information.

In [2]:
A = torch.Tensor([[1, 2, 3], [2, 4, 6], [5, 7, 2]])
print("A: \n", A)
A.inverse()

A: 
 tensor([[1., 2., 3.],
        [2., 4., 6.],
        [5., 7., 2.]])


RuntimeError: Lapack Error getrf : U(3,3) is 0, U is singular at /pytorch/aten/src/TH/generic/THTensorLapack.cpp:572

We also get an error if the matrix is not square, which means the dimension of vector b and A's row are different.

In [3]:
A = torch.Tensor([[1, 2, 3], [5, 7, 2]])
print("A: \n", A)
A.inverse()

A: 
 tensor([[1., 2., 3.],
        [5., 7., 2.]])


RuntimeError: invalid argument 1: A should be square at /pytorch/aten/src/TH/generic/THTensorLapack.cpp:551

### Linearly independent matrix example
We can successfully calculate the inverse of the square matrix which is not singular.

In [4]:
A = torch.Tensor([[1, 2, 3], [2, 4, 9], [5, 7, 2]])
print("A: \n", A)
print("A^-1: \n", A.inverse())

A: 
 tensor([[1., 2., 3.],
        [2., 4., 9.],
        [5., 7., 2.]])
A^-1: 
 tensor([[-6.1111e+00,  1.8889e+00,  6.6667e-01],
        [ 4.5556e+00, -1.4444e+00, -3.3333e-01],
        [-6.6667e-01,  3.3333e-01, -9.9341e-10]])


In [5]:
print("AA^-1: \n", A.matmul(A.inverse()).round().int())

AA^-1: 
 tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]], dtype=torch.int32)


Again, here I'm using very sloppy rounding to show the identity matrix by a simple way.