# 2 Linear Algebra

## 2.8 Singular Value Decomposition

In [1]:
import torch

In [2]:
A = torch.FloatTensor([[7,5,7], [9,1,3]])
print("A: \n", A)

A: 
 tensor([[7., 5., 7.],
        [9., 1., 3.]])


In [3]:
U_eigval, U = A.matmul(A.t()).eig(eigenvectors=True)
V_eigval, V = A.t().matmul(A).eig(eigenvectors=True)
D_tmp = (U_eigval ** (1/2))[:,0].diag()

D = torch.zeros(U.size()[0], V.size()[0])
D[:,:-1] = D_tmp

print("U: \n", U)
print("D: \n", D)
print("V: \n", V)

U: 
 tensor([[ 0.7671, -0.6415],
        [ 0.6415,  0.7671]])
D: 
 tensor([[14.0509,  0.0000,  0.0000],
        [ 0.0000,  4.0710,  0.0000]])
V: 
 tensor([[ 0.7931,  0.5929, -0.1399],
        [ 0.3186, -0.5995, -0.7342],
        [ 0.5191, -0.5377,  0.6643]])


In [4]:
U, D_tmp, V = A.svd(some=False)

D = torch.zeros([U.size()[0], V.size()[0]])
D[:,:-1] = D_tmp.diag()

print("U: \n", U)
print("D: \n", D)
print("V: \n", V)
print("Singular decomposition of A: \n", U.matmul(D).matmul(V.t()))

U: 
 tensor([[-0.7671, -0.6415],
        [-0.6415,  0.7671]])
D: 
 tensor([[14.0509,  0.0000,  0.0000],
        [ 0.0000,  4.0710,  0.0000]])
V: 
 tensor([[-0.7931,  0.5929, -0.1399],
        [-0.3186, -0.5995, -0.7342],
        [-0.5191, -0.5377,  0.6643]])
Singular decomposition of A: 
 tensor([[7.0000, 5.0000, 7.0000],
        [9.0000, 1.0000, 3.0000]])


By default, svd function in PyTorch internally takes min(m, n) orthonormal vectors (where m, n are the numbers of rows and columns of A), which sometimes makes V not a square matrix of shape (n, n) and D a square matrix:

In [5]:
U, D, V = A.svd()
D = D.diag()

print("U: \n", U)
print("D: \n", D)
print("V: \n", V)
print("Singular decomposition of A: \n", U.matmul(D).matmul(V.t()))

U: 
 tensor([[-0.7671, -0.6415],
        [-0.6415,  0.7671]])
D: 
 tensor([[14.0509,  0.0000],
        [ 0.0000,  4.0710]])
V: 
 tensor([[-0.7931,  0.5929],
        [-0.3186, -0.5995],
        [-0.5191, -0.5377]])
Singular decomposition of A: 
 tensor([[7.0000, 5.0000, 7.0000],
        [9.0000, 1.0000, 3.0000]])
